=== SJSU-PER/SE157B-02/book.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:complexType name="book_type">
      <xs:sequence>
         <xs:element name="book_id" type="xs:integer"/>
         <xs:element name="pub_date" type="xs:string"/>
         <xs:element name="title" type="xs:string"/>
         <xs:element name="isbn_id" type="xs:integer"/>
         <xs:element name="pub_id" type="xs:integer"/>
      </xs:sequence>
   </xs:complexType>

   <xs:element name="book_info" type="book_type"/>

   <xs:complexType name="book_root">
      <xs:sequence>
         <xs:element ref="book_info" minOccurs="0"
                        maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>

   <xs:element name="book" type="book_root"/>
</xs:schema>

=== SJSU-PER/SE157B-02/src/book.xml
<?xml version="1.0"?>

<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="book.xsd">
   <book_info>
      <book_id>1</book_id>
      <pub_date>2008</pub_date>
      <title>Bag of Bones</title>
      <isbn_id>1</isbn_id>
      <pub_id>1</pub_id>
   </book_info>

   <book_info>
      <book_id>2</book_id>
      <pub_date>1933</pub_date>
      <title>Lost Horizon</title>
      <isbn_id>2</isbn_id>
      <pub_id>1</pub_id>
   </book_info>

   <book_info>
      <book_id>3</book_id>
      <pub_date>1923</pub_date>
      <title>Bambi: A Life in the Woods</title>
      <isbn_id>3</isbn_id>
      <pub_id>1</pub_id>
   </book_info>

   <book_info>
      <book_id>4</book_id>
      <pub_date>2008</pub_date>
      <title>Database Systems, the Complete Book</title>
      <isbn_id>4</isbn_id>
      <pub_id>2</pub_id>
   </book_info>

   <book_info>
      <book_id>5</book_id>
      <pub_date>1998</pub_date>
      <title>Algebra: Tools for a Changing World</title>
      <isbn_id>5</isbn_id>
      <pub_id>3</pub_id>
   </book_info>

   <book_info>
      <book_id>6</book_id>
      <pub_date>2009</pub_date>
      <title>Under the Dome</title>
      <isbn_id>6</isbn_id>
      <pub_id>4</pub_id>
   </book_info>

   <book_info>
      <book_id>7</book_id>
      <pub_date>2002</pub_date>
      <title>Murder at School</title>
      <isbn_id>7</isbn_id>
      <pub_id>5</pub_id>
   </book_info>

   <book_info>
      <book_id>8</book_id>
      <pub_date>1977</pub_date>
      <title>The Shining</title>
      <isbn_id>8</isbn_id>
      <pub_id>4</pub_id>
   </book_info>

   <book_info>
      <book_id>9</book_id>
      <pub_date>1975</pub_date>
      <title>Salem's Lot</title>
      <isbn_id>9</isbn_id>
      <pub_id>6</pub_id>
   </book_info>
</book>
