=== SJSU-PER/SE157B-02/src/author.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:complexType name="author_type">
      <xs:sequence>
         <xs:element name="author_id" type="xs:string"/>
         <xs:element name="first_name" type="xs:string"/>
         <xs:element name="last_name" type="xs:string"/>
      </xs:sequence>
   </xs:complexType>

   <xs:element name="author_info" type="author_type"/>

   <xs:complexType name="author_root">
      <xs:sequence>
         <xs:element ref="author_info" minOccurs="0"
                        maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>

   <xs:element name="author" type="author_root"/>
</xs:schema>

=== SJSU-PER/SE157B-02/src/author.xml
<?xml version="1.0"?>

<author xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="author.xsd">
   <author_info>
      <author_id>1</author_id>
      <first_name>Stephen</first_name>
      <last_name>King</last_name>
   </author_info>

   <author_info>
      <author_id>2</author_id>
      <first_name>James</first_name>
      <last_name>Hilton</last_name>
   </author_info>

   <author_info>
      <author_id>3</author_id>
      <first_name>Felix</first_name>
      <last_name>Salten</last_name>
   </author_info>

   <author_info>
      <author_id>4</author_id>
      <first_name>Hector</first_name>
      <last_name>Garcia-Milina</last_name>
   </author_info>

   <author_info>
      <author_id>5</author_id>
      <first_name>Jeffry</first_name>
      <last_name>Ullman</last_name>
   </author_info>

   <author_info>
      <author_id>6</author_id>
      <first_name>Jennifer</first_name>
      <last_name>Widom</last_name>
   </author_info>

   <author_info>
      <author_id>7</author_id>
      <first_name>Prentice</first_name>
      <last_name>Hall</last_name>
   </author_info>
</author>
