=== SJSU-PER/SE157B-02/src/book_author.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:complexType name="book_author_type">
      <xs:sequence>
         <xs:element name="author_id" type="xs:long"/>
         <xs:element name="book_id" type="xs:long"/>
      </xs:sequence>
   </xs:complexType>

   <xs:element name="book_author_info" type="book_author_type"/>

   <xs:complexType name="book_author_root">
      <xs:sequence>
         <xs:element ref="book_author_info" minOccurs="0"
                     maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>

   <xs:element name="book_author" type="book_author_root"/>
</xs:schema>

=== SJSU-PER/SE157B-02/src/book_author.xml
<?xml version="1.0"?>

<book_author xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="book_author.xsd">
   <book_author_info>
      <author_id>1</author_id>
      <book_id>1</book_id>
   </book_author_info>

   <book_author_info>
      <author_id>2</author_id>
      <book_id>2</book_id>
   </book_author_info>

   <book_author_info>
      <author_id>3</author_id>
      <book_id>3</book_id>
   </book_author_info>

   <book_author_info>
      <author_id>6</author_id>
      <book_id>4</book_id>
   </book_author_info>

   <book_author_info>
      <author_id>4</author_id>
      <book_id>4</book_id>
   </book_author_info>

   <book_author_info>
      <author_id>5</author_id>
      <book_id>4</book_id>
   </book_author_info>

   <book_author_info>
      <author_id>7</author_id>
      <book_id>5</book_id>
   </book_author_info>

   <book_author_info>
      <author_id>1</author_id>
      <book_id>6</book_id>
   </book_author_info>

   <book_author_info>
      <author_id>2</author_id>
      <book_id>7</book_id>
   </book_author_info>

   <book_author_info>
      <author_id>1</author_id>
      <book_id>8</book_id>
   </book_author_info>

   <book_author_info>
      <author_id>1</author_id>
      <book_id>9</book_id>
   </book_author_info>
</book_author>
