=== SJSU-PER/SE157B-02/src/publisher.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:complexType name="publisher_type">
      <xs:sequence>
         <xs:element name="pub_id" type="xs:integer"/>
         <xs:element name="pub_name" type="xs:string"/>
      </xs:sequence>
   </xs:complexType>

   <xs:element name="pub_info" type="publisher_type"/>

   <xs:complexType name="publisher_root">
      <xs:sequence>
         <xs:element ref="pub_info" minOccurs="0"
                        maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>

   <xs:element name="publisher" type="publisher_root"/>
</xs:schema>

=== SJSU-PER/SE157B-02/src/publisher.xml
<?xml version="1.0"?>

<publisher xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="publisher.xsd">
   <pub_info>
      <pub_id>1</pub_id>
      <pub_name>Pocket Books</pub_name>
   </pub_info>

   <pub_info>
      <pub_id>2</pub_id>
      <pub_name>Pearson</pub_name>
   </pub_info>

   <pub_info>
      <pub_id>3</pub_id>
      <pub_name>Prentice Hall</pub_name>
   </pub_info>

   <pub_info>
      <pub_id>4</pub_id>
      <pub_name>Gallery Books</pub_name>
   </pub_info>

   <pub_info>
      <pub_id>5</pub_id>
      <pub_name>Dales Large Print Books</pub_name>
   </pub_info>

   <pub_info>
      <pub_id>6</pub_id>
      <pub_name>Random House Digital, Inc</pub_name>
   </pub_info>
</publisher>
